version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

